# Project: list
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = list.o
LINKOBJ  = list.o
LIBS     = -L"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/include" -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/include" -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Software/DevC++/DevC++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = list.exe
CXXFLAGS = $(CXXINCS) -fexec-charset=gbk
CFLAGS   = $(INCS) -fexec-charset=gbk
DEL      = D:\Software\DevC++\DevC++\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

list.o: list.cpp
	$(CPP) -c list.cpp -o list.o $(CXXFLAGS)
